### ISSUE TITLE
Cannot load auth from ~/.docker/config.json

### ISSUE THREAD

**Issue by stigkj** [chrisgahlert/gradle-dcompose-plugin#17]
We have a private repository and have the auth info in the `~/.docker/config.json`. This looks something like this:

```
{
    "auths": {
        "<registry hostname>": {
            "auth": "dGVzdC11aWQ6dGVzdC1wd2Q="
        }
    },
    "HttpHeaders": {
        "User-Agent": "Docker-Client/18.05.0-ce (darwin)"
    }
}
```

The problem is that the plugin is not reading this value but just sends empty auth values. To get it to work we had to

1. read the auth value from the file
2. extract username and password from the value
3. set these in a `registry` section for the plugin

We get this error when the plugin tries to fetch an image:

```
Caused by: org.gradle.api.GradleException: Docker command failed: Could not build image: Get https://<repository hostname>/v2/x/y/manifests/10: unknown: Authentication is required
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.chrisgahlert.gradledcomposeplugin.tasks.AbstractDcomposeTask.runInDockerClasspath(AbstractDcomposeTask.groovy:179)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.chrisgahlert.gradledcomposeplugin.tasks.image.DcomposeImageBuildTask.buildImage(DcomposeImageBuildTask.groovy:93)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: com.github.dockerjava.api.exception.DockerClientException: Could not build image: Get https://<repository hostname>/v2/x/y/manifests/10: unknown: Authentication is required
        at com.github.dockerjava.core.command.BuildImageResultCallback.getImageId(BuildImageResultCallback.java:79)
        at com.github.dockerjava.core.command.BuildImageResultCallback.awaitImageId(BuildImageResultCallback.java:51)
        at com.github.dockerjava.core.command.BuildImageResultCallback$awaitImageId.call(Unknown Source)
        at com.github.dockerjava.core.command.BuildImageResultCallback$awaitImageId.call(Unknown Source)
        at com.chrisgahlert.gradledcomposeplugin.tasks.image.DcomposeImageBuildTask$_buildImage_closure3.doCall(DcomposeImageBuildTask.groovy:128)
        at com.chrisgahlert.gradledcomposeplugin.tasks.image.DcomposeImageBuildTask$_buildImage_closure3.doCall(DcomposeImageBuildTask.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.chrisgahlert.gradledcomposeplugin.tasks.AbstractDcomposeTask.runInDockerClasspath(AbstractDcomposeTask.groovy:177)
        ... 52 more
```

We have tried another plugin that uses the docker-java library and that one works. This seems to be a problem with how the library is used.

**Comment by chrisgahlert** [comment]
That's strange as I implemented the support for the `~/.docker/config.json` file in version `0.10.0`...

Can you confirm, that you are using that version and that the `<registry hostname>` is just the hostname (without `http(s)://`)?

**Comment by chrisgahlert** [comment]
Does the problem still exist?
