### ISSUE TITLE
Can't run multiple "waitForCommand" services in single gradle exection.

### ISSUE THREAD

**Issue by sfitts** [chrisgahlert/gradle-dcompose-plugin#20]
When we try to create multiple tasks, each of which will cause a "waitForCommand" service to execution we get the following exception:

```
Caused by: org.gradle.api.GradleException: Docker command failed: There's an extension registered with name 'exitCode'. You should not reassign it via a property setter.
        at com.chrisgahlert.gradledcomposeplugin.utils.DockerExecutor.runInDockerClasspath(DockerExecutor.groovy:34)
        at com.chrisgahlert.gradledcomposeplugin.utils.DockerExecutor$runInDockerClasspath$0.call(Unknown Source)
        at com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStartTask.startContainer(DcomposeContainerStartTask.groovy:89)
        at com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStartTask$startContainer.call(Unknown Source)
```

I think this is due to the following line of code at line 109 in `DcomposeContainerStartTask`:

```
extensions.exitCode = service.exitCode
```

Given that the exit code is stored in the service it doesn't seem necessary to also store it as an "extension" object as well, but I'm obviously not sure what use case is being addressed here.

**Comment by chrisgahlert** [comment]
I'm guessing that you are trying to execute the same task twice with different properties. If that's the case you could also create another start tasks for your container:

```gradle
task startMyContainerAnotherTime(type: com.chrisgahlert.gradledcomposeplugin.tasks.container.DcomposeContainerStartTask) {
  service = dcompose.myService
}
```

I haven't tested this, but in theory it should work! ^^

Please let me know, how it goes! ;)

**Comment by chrisgahlert** [comment]
I added a new check to prevent this error in version `0.12.0` available now.

**Comment by sfitts** [comment]
Thanks much -- I'll give it a try today.
