### ISSUE TITLE
ClassCastException with 0.16.4

### ISSUE THREAD

**Issue by henrik242** [chrisgahlert/gradle-dcompose-plugin#34]
I get a ClassCastException with 0.16.4.  0.16.3 does not have this problem.  It's really weird, because I can't really see anything in [the diff](https://github.com/chrisgahlert/gradle-dcompose-plugin/compare/v0.16.3...v0.16.4) that should cause this.

```
:pale-pp-web:startSolrContainer (Thread[Execution worker for ':',5,main]) started.

FAILURE: Build failed with an exception.

* What went wrong:
ClassCastException: attempting to castjar:file:/Users/foo/.gradle/caches/jars-8/c36ad1861fd5cbd3b1b02659c2ba998c/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/Users/foo/.gradle/caches/modules-2/files-2.1/jakarta.ws.rs/jakarta.ws.rs-api/2.1.6/1dcb770bce80a490dff49729b99c7a60e9ecb122/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/client/ClientBuilder.class

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:

* What went wrong:
ClassCastException: attempting to castjar:file:/Users/foo/.gradle/caches/jars-8/c36ad1861fd5cbd3b1b02659c2ba998c/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/Users/foo/.gradle/caches/modules-2/files-2.1/jakarta.ws.rs/jakarta.ws.rs-api/2.1.6/1dcb770bce80a490dff49729b99c7a60e9ecb122/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/client/ClientBuilder.class

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.LinkageError: ClassCastException: attempting to castjar:file:/Users/foo/.gradle/caches/jars-8/c36ad1861fd5cbd3b1b02659c2ba998c/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/client/ClientBuilder.class to jar:file:/Users/foo/.gradle/caches/modules-2/files-2.1/jakarta.ws.rs/jakarta.ws.rs-api/2.1.6/1dcb770bce80a490dff49729b99c7a60e9ecb122/jakarta.ws.rs-api-2.1.6.jar!/javax/ws/rs/client/ClientBuilder.class
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.<init>(JerseyDockerHttpClient.java:253)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient.<init>(JerseyDockerHttpClient.java:45)
        at com.github.dockerjava.jaxrs.JerseyDockerHttpClient$Builder.build(JerseyDockerHttpClient.java:120)
        at com.github.dockerjava.jaxrs.JerseyDockerCmdExecFactory.init(JerseyDockerCmdExecFactory.java:44)
        at com.github.dockerjava.core.DockerClientImpl.withDockerCmdExecFactory(DockerClientImpl.java:242)
        at com.github.dockerjava.core.DockerClientBuilder.build(DockerClientBuilder.java:93)
        at com.github.dockerjava.core.DockerClientBuilder$build$1.call(Unknown Source)
        at com.chrisgahlert.gradledcomposeplugin.utils.DockerExecutor.getClient(DockerExecutor.groovy:69)
```

**Comment by henrik242** [comment]
Seems like `jakarta.ws.rs-api-2.1.6.jar` has a different checksum? That doesn't seem too good.

**Comment by chrisgahlert** [comment]
I really can't explain this error... could you try clearing local caches? 

If that doesn't help: Could you try to recreate the problem on a test project?

**Comment by henrik242** [comment]
Somehow I have two different versions of jakarta.ws.rs-api-2.1.6.jar:
```
333756 11 aug 09:02 .gradle/caches/jars-8/c36ad1861fd5cbd3b1b02659c2ba998c/jakarta.ws.rs-api-2.1.6.jar
140376 21 feb  2020 .gradle/caches/modules-2/files-2.1/jakarta.ws.rs/jakarta.ws.rs-api/2.1.6/1dcb770bce80a490dff49729b99c7a60e9ecb122/jakarta.ws.rs-api-2.1.6.jar
```
 .. with slightly different content:
```
@@ -27,8 +27,8 @@
 1467 javax/ws/rs/sse/SseEventSource.class
 1511 javax/ws/rs/core/Form.class
 1633 javax/ws/rs/client/ClientResponseContext.class
-1646 META-INF/MANIFEST.MF
-1667 javax/ws/rs/core/Response$Status$Family.class
+1642 META-INF/MANIFEST.MF
+1664 javax/ws/rs/core/Response$Status$Family.class
 1706 javax/ws/rs/container/ContainerRequestContext.class
 171 javax/ws/rs/core/Feature.class
 1744 javax/ws/rs/ext/MessageBodyWriter.class
@@ -78,7 +78,7 @@
 3500 javax/ws/rs/client/ClientBuilder.class
 35025 META-INF/maven/jakarta.ws.rs/jakarta.ws.rs-api/pom.xml
 35084 META-INF/LICENSE.md
-3658 javax/ws/rs/NotAllowedException.class
+3624 javax/ws/rs/NotAllowedException.class
 372 javax/ws/rs/container/ResourceContext.class
 3815 javax/ws/rs/core/UriBuilder.class
 3893 javax/ws/rs/client/AsyncInvoker.class
@@ -86,17 +86,17 @@
 391 javax/ws/rs/sse/SseEventSink.class
 4186 javax/ws/rs/ext/RuntimeDelegate.class
 423 javax/ws/rs/ext/Provider.class
-4285 javax/ws/rs/NotAuthorizedException.class
+4251 javax/ws/rs/NotAuthorizedException.class
 435 javax/ws/rs/container/PreMatching.class
 436 javax/ws/rs/NameBinding.class
 436 javax/ws/rs/container/Suspended.class
 440 javax/ws/rs/ext/ParamConverterProvider.class
 4468 javax/ws/rs/core/Variant.class
+4506 javax/ws/rs/ServiceUnavailableException.class
 453 javax/ws/rs/BeanParam.class
 453 javax/ws/rs/GET.class
 453 javax/ws/rs/PUT.class
 454 javax/ws/rs/core/Context.class
-4540 javax/ws/rs/ServiceUnavailableException.class
 456 javax/ws/rs/HEAD.class
 456 javax/ws/rs/POST.class
 456 javax/ws/rs/Path.class
@@ -126,20 +126,20 @@
 542 javax/ws/rs/Consumes.class
 542 javax/ws/rs/Produces.class
 568 module-info.class
-5739 javax/ws/rs/core/Response$Status.class
+5759 javax/ws/rs/core/Response$Status.class
 577 javax/ws/rs/ext/ReaderInterceptorContext.class
 5786 javax/ws/rs/client/CompletionStageRxInvoker.class
 5914 javax/ws/rs/core/CacheControl.class
-6427 javax/ws/rs/ext/FactoryFinder.class
-6427 javax/ws/rs/sse/FactoryFinder.class
-6433 javax/ws/rs/client/FactoryFinder.class
 651 javax/ws/rs/ext/WriterInterceptorContext.class
+6574 javax/ws/rs/ext/FactoryFinder.class
+6574 javax/ws/rs/sse/FactoryFinder.class
+6583 javax/ws/rs/client/FactoryFinder.class
 666 javax/ws/rs/core/Form$1.class
 688 javax/ws/rs/HttpMethod.class
 6996 javax/ws/rs/core/Response.class
 7080 javax/ws/rs/client/Entity.class
 711 javax/ws/rs/sse/SseBroadcaster.class
-7150 javax/ws/rs/core/MediaType.class
+7163 javax/ws/rs/core/MediaType.class
 7249 javax/ws/rs/core/AbstractMultivaluedMap.class
 731 javax/ws/rs/ProcessingException.class
 731 javax/ws/rs/core/NoContentException.class
@@ -155,6 +155,6 @@
 922 javax/ws/rs/core/MediaType$1.class
 929 javax/ws/rs/ext/InterceptorContext.class
 950 javax/ws/rs/ext/MessageBodyReader.class
-959 javax/ws/rs/RuntimeType.class
+956 javax/ws/rs/RuntimeType.class
```
And even some tiny differences in MANIFEST.MF:
```
@@ -6,8 +6,8 @@
 Built-By: default
 Bundle-Description: Jakarta RESTful Web Services API
 Bundle-DocURL: https://www.eclipse.org/org/foundation/
-Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.or
- g/software/classpath/license.html
+Bundle-License: http://www.eclipse.org/legal/epl-2.0, https://www.gnu.
+ org/software/classpath/license.html
 Bundle-ManifestVersion: 2
 Bundle-Name: jakarta.ws.rs-api
 Bundle-SymbolicName: jakarta.ws.rs-api
@@ -15,21 +15,22 @@
 Bundle-Version: 2.1.6
 Created-By: Apache Maven Bundle Plugin
 DynamicImport-Package: *
-Export-Package: javax.ws.rs.client;version="2.1.6";uses:="javax.net.ssl,
- javax.ws.rs,javax.ws.rs.core",javax.ws.rs;version="2.1.6";uses:="javax.
- ws.rs.core",javax.ws.rs.core;version="2.1.6";uses:="javax.ws.rs,javax.x
- ml.bind.annotation,javax.xml.bind.annotation.adapters,javax.xml.namespa
- ce",javax.ws.rs.container;version="2.1.6";uses:="javax.ws.rs.core",java
- x.ws.rs.ext;version="2.1.6";uses:="javax.ws.rs,javax.ws.rs.core",javax.
- ws.rs.sse;version="2.1.6";uses:="javax.ws.rs.client,javax.ws.rs.core"
+Export-Package: javax.ws.rs.client;version="2.1.6";uses:="javax.net.ss
+ l,javax.ws.rs,javax.ws.rs.core",javax.ws.rs;version="2.1.6";uses:="ja
+ vax.ws.rs.core",javax.ws.rs.core;version="2.1.6";uses:="javax.ws.rs,j
+ avax.xml.bind.annotation,javax.xml.bind.annotation.adapters,javax.xml
+ .namespace",javax.ws.rs.container;version="2.1.6";uses:="javax.ws.rs.
+ core",javax.ws.rs.ext;version="2.1.6";uses:="javax.ws.rs,javax.ws.rs.
+ core",javax.ws.rs.sse;version="2.1.6";uses:="javax.ws.rs.client,javax
+ .ws.rs.core"
 Extension-Name: javax.ws.rs
 Implementation-Version: 2.1.6
-Import-Package: javax.net.ssl,javax.ws.rs;version="[2.1,3)",javax.ws.rs.
- client;version="[2.1,3)",javax.ws.rs.core;version="[2.1,3)",javax.ws.rs
- .ext;version="[2.1,3)",javax.xml.bind.annotation;version="[2.3,3)",java
- x.xml.bind.annotation.adapters;version="[2.3,3)",javax.xml.namespace
+Import-Package: javax.net.ssl,javax.ws.rs;version="[2.1,3)",javax.ws.r
+ s.client;version="[2.1,3)",javax.ws.rs.core;version="[2.1,3)",javax.w
+ s.rs.ext;version="[2.1,3)",javax.xml.bind.annotation;version="[2.3,3)
+ ",javax.xml.bind.annotation.adapters;version="[2.3,3)",javax.xml.name
+ space
 Require-Capability: osgi.ee;filter:="(&(osgi.ee=JavaSE)(version=1.8))"
 Specification-Vendor: Oracle Corporation
 Specification-Version: 2.1
 Tool: Bnd-3.5.0.201709291849
```
`file` reports some differences that I don't quite comprehend (even though file sizes **and decompiled classes** are the same!):
```
old/javax/ws/rs/client/ClientBuilder.class:  [64-bit architecture=458848] [architecture=393315] [architecture=6752768] [] [architecture=7408128]
new/javax/ws/rs/client/ClientBuilder.class:     [64-bit architecture=7238703] [64-bit architecture=21836] [64-bit architecture=5007969] [64-bit architecture=7235177] [64-bit architecture=3109491]
```
Deleting `~/.gradle` didn't solve the issue.  I'll keep investigating!

(Sorry about all the content in this comment, I just wanted to document my findings somewhere :) )

**Comment by henrik242** [comment]
I figured it out!  I had a dependency to docker-java in `buildscript`:
```
buildscript {
  [...]
  dependencies {
    classpath("gradle.plugin.com.chrisgahlert:gradle-dcompose-plugin:0.16.4")
    classpath("com.github.docker-java:docker-java:3.2.5")
  }
}
```
Removing the docker-java dependency fixed the issue.  I still don't understand why it didn't fail on `0.16.3` and earlier.

**Comment by chrisgahlert** [comment]
👍  ;)
